<?php

$modversion['name'] = 'Webcam-portail';
$modversion['version'] = '1.1';
$modversion['description'] = 'un module portail de webcam pour xoop';
$modversion['credits'] = 'Créé et Modularisé pour XOOPS par<br>Bidou <br>( http://www.lespace.org/ )<br> Arrangé pour xoops 2.0.5.1 par sylvain B.';
$modversion['author'] = 'Original webcam-portail 1.0b par<br>El Bidou<br>( http://www.lespace.org/ )';
$modversion['help'] = 'newbb.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = '0';
$modversion['image'] = 'images/webcam.jpg';
$modversion['dirname'] = 'camportail';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminpath'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Menu
$modversion['hasMain'] = 1;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'docs/sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'camportail';
$modversion['tables'][1] = 'camportail_cat';
$modversion['tables'][2] = 'camportail_comment';
$modversion['tables'][3] = 'camportail_control';
$modversion['tables'][4] = 'camportail_souscat';







